### ISSUE TITLE
拼音展示错位，可以在此处留下你的浏览器版本和系统 🙏🏻🙏🏻🙏🏻

### ISSUE THREAD

**Issue by meetqy** [meetqy/aspoem#10]
由于拼音带了声调，有些字体展示异常，大部分的原因是因为，`font-family` 预设的问题，需要对不同的浏览器和版本进行适配。

现在是用的 tailwindcss 自带的 `font-serif`，在不同的浏览器和版本中，可能会有差异。所以可能需要自定义 `font-serif`。

如果你遇到了拼音错位的问题，可以在此处留下你的 浏览器/浏览器版本号/系统/拼音展示错误的链接。

```md
浏览器: Chrome 120.0.6099.234
系统:   Macos
链接:   https://aspoem.com/poem/22
```

**Comment by Desperado2** [comment]
浏览器: Chrome 120.0.6099.225（正式版本） （64 位）
系统:   Windows 10 专业工作站版
链接:  https://aspoem.com/poem/569?py=t
![image](https://github.com/meetqy/aspoem/assets/23252897/3573e7b7-f32e-4e25-8cfd-7322b4b17bfb)

**Comment by jizhang02** [comment]
浏览器: Edge Version 120.0.2210.144 (Official build) (64-bit)
系统:   Windows 10
链接:   https://aspoem.com/poem/157?py=t
![image](https://github.com/meetqy/aspoem/assets/46089068/c927a0a1-c49d-46c8-b161-5287344e947a)

**Comment by meetqy** [comment]
- [ ] https://github.com/meetqy/aspoem/issues/10#issuecomment-1912152943

**Comment by gotnix** [comment]
据我的观察，只有第 3 声的声调才会有这个情况，和拼音的字母没有关系。
|操作系统|浏览器|拼音展示错位情况|
|----------|--------|--------------------|
|Windows 11 Version 22H2 (Build 22621.2070)|Microsoft Edge：123.0.2420.65 (正式版本) (64 位)<br>Chromium 版本：123.0.6312.87|第3声错位|
|同上|Google Chrome：122.0.6261.112 (正式版本) （64 位）|同上|
|同上|Brave 1.63.169 Chromium：122.0.6261.111 (正式版本) （64 位）|同上|
|同上|Mozilla Firefox：124.0.2 （64 位）|正常|

链接：https://aspoem.com/zh-Hans/poem/200?py=t

**Comment by gotnix** [comment]
十分感谢 @meetqy ，现在都显示正常了。
