### ISSUE TITLE
拼音系统无法正确处理多音字

### ISSUE THREAD

**Issue by chesha1** [meetqy/aspoem#160]
在 [滕王阁序](https://aspoem.com/zh-Hans/poem/2255?py=t) 中

> 宁移白首之心

中宁被表示为 ning2

> 访风景于崇阿

中阿被表示为 a1

这些拼音是系统自动生成的, 还是记录在数据库里, 单纯是这两个地方数据错了?

**Comment by meetqy** [comment]
数据是存在数据库中的，不过初版的数据数自动生成的，后续会通过 #108 的方式去校对
