### ISSUE TITLE
补一首诗 春夜喜雨 

### ISSUE THREAD

**Issue by kangyunjie** [meetqy/aspoem#19]
**春夜喜雨**
唐 杜甫
好雨知时节，当春乃发生。
随风潜入夜，润物细无声。
野径云俱黑，江船火独明。
晓看红湿处，花重锦官城。

**Comment by meetqy** [comment]
已添加 https://aspoem.com/poem/2132

**Comment by kangyunjie** [comment]
> 已添加 https://aspoem.com/poem/2132

开工大吉
