### ISSUE TITLE
词句错误问题

### ISSUE THREAD

**Issue by shaoao** [meetqy/aspoem#28]
黄鹤楼送孟浩然之广陵

孤帆远影碧空尽，你写成孤帆远影碧山尽了。

可以去检查一下，不过这是我第一次访问这个诗词网站，然后打开的第一首诗，就发现了这个小错误

**Comment by meetqy** [comment]
是的，确实应该是 “碧空尽”。已更正。

你的主页泰裤辣。👍🏻
