### ISSUE TITLE
手机VIA浏览器浏览具体诗词的时候太宽，需要缩放下才行

### ISSUE THREAD

**Issue by rocex** [meetqy/aspoem#35]
华为mate30 emui10.1 用via查看具体诗词时太宽，需要缩放下才行，微信浏览没问题。
也不是全这样，柳宗元的江雪就太宽了，李清照的武陵春 春晚就刚好。

**Comment by meetqy** [comment]
可以看看截图吗，手机的型号太多了，没办法一一去验证。

**Comment by rocex** [comment]
一对一错

![Screenshot_20240309_144349_mark via](https://github.com/meetqy/aspoem/assets/9346138/e9403728-4ed4-443d-8d20-bcadebb4b788)
![Screenshot_20240309_144326_mark via](https://github.com/meetqy/aspoem/assets/9346138/dbdf4e90-93e7-47c3-a0f9-0dcd602f759f)

**Comment by rocex** [comment]
firefox 120.0.1 响应模式就可以重现。

![2024-03-09_145127](https://github.com/meetqy/aspoem/assets/9346138/54602442-d2a1-45fc-9428-b34ae4ea6f3b)

**Comment by meetqy** [comment]
已修复
