### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by spearous** [meetqy/aspoem#39]
1. 打印版本能不能加上拼音打印功能？（比如网页打开了拼音，那么打印版就把拼音一起打；如果网页没开拼音，那打印版就不加拼音）
2. 下面注释部分能不能也加上拼音。

主要是给小学低年级孩子看，如果加上了拼音，他们自己就可以按照兴趣随时复习。

谢谢

**Comment by meetqy** [comment]
1. 诗词加上拼音是有计划的
2. 注释加拼音应该不行，拼音没结果校验可能会有错误，注释还不好去做校验。
