### ISSUE TITLE
增加一键部署

### ISSUE THREAD

**Issue by oulin52** [meetqy/aspoem#42]
大佬可以增加一键部署吗?

**Comment by meetqy** [comment]
现在事情太多了，暂时没有时间去做一键部署，部署到 vercel 还要去看文档。

话说你本地能跑的话，部署其他平台应该就非常简单了吧。

**Comment by zoblion** [comment]
小白比较菜，非码农，大佬有时间的话求个一键部署到docker之类的，万分感激。
