### ISSUE TITLE
按照文档上的本地部署，链接不上数据库

### ISSUE THREAD

**Issue by cannot-hero** [meetqy/aspoem#51]
```
Unhandled Runtime Error
Error: 
Invalid `prisma.$queryRaw()` invocation:


Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
```

windows环境，按照文档上复制的做的本地配置，但是链接不上数据库

第一次用postgre，问的问题可能比较蠢，希望能帮忙解决此问题

**Comment by meetqy** [comment]
<img width="1050" alt="image" src="https://github.com/meetqy/aspoem/assets/18411315/159fec2e-8d3f-4275-8a25-0963a9b1595a">

重新更新了一份 readme 文档，你可以看下

**Comment by cannot-hero** [comment]
```
Error: 
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `1`. Message: `no such table: public.Poem`
```
按照新的readme修改为sqlite,但是Prisma好像没有自动建表

**Comment by meetqy** [comment]
<img width="340" alt="image" src="https://github.com/meetqy/aspoem/assets/18411315/9720e610-c8a4-4768-9500-940c90da627b">
执行成功会在本地生成一个db.sqlite 数据文件，但是没有数据，你需要再 /create 里面去添加数据

**Comment by iamflowerdog** [comment]
之前的版本：http://localhost:3000/create/table 里面有一些诗词，可以本地快速添加，是在content.json 文件里面。目前版本没有了，这个挺好用，希望可以回归

**Comment by iamflowerdog** [comment]
按照本地部署，我到localhost添加数据后，也继续提示上面的错误。
![image](https://github.com/meetqy/aspoem/assets/27678693/057f58f7-54d3-439a-aac8-7c89c5c7d6a9)
下面是数据库添加成功截图：
![image](https://github.com/meetqy/aspoem/assets/27678693/f3a1c08c-cb1f-45a0-a9f6-2e25804d0caa)

**Comment by meetqy** [comment]
好的，非常感谢，已经解决了，你可以拉去最新的代码试试

> sqlite 好像不支持 public 写法

**Comment by meetqy** [comment]
> 之前的版本：http://localhost:3000/create/table 里面有一些诗词，可以本地快速添加，是在content.json 文件里面。目前版本没有了，这个挺好用，希望可以回归

会用 #53 功能替代掉，直接内置 db.sqlite 的 mock 数据
